# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
	# Method for displaying the page tiltle.
	def page_title
		controller=controller_name
		action=action_name
		if controller == "manage_profiles"
			if action == "login_manage" && params[:login] && params[:login] == "mc"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "login_manage"
				return_title = "Consent Request"
			elsif action == "login_retry"
				return_title = "Retry, Match Fail | AT&T"
			elsif action == "registration" || action == "off_network_registration"
				return_title = "Sign up for AT&T"
			elsif action == "signup_retry"
				return_title = "Sign up for AT&T"
			elsif action == "activation"
				return_title = "Sign up for AT&T"
			elsif action == "signup_create"
				return_title = "Sign up for AT&T"
			elsif action == "resend_mobile_pin"
				return_title = "Sign up for AT&T"
			elsif action == "resend_email_pin"
				return_title = "Sign up for AT&T"
			elsif action == "validate_pin"
				return_title = "Sign up for AT&T"
			elsif action == "signup_confirmation"
				return_title = "Account Created | AT&amp;T"
			elsif action == "reset_password"
				return_title = "Manage Password | AT&T"
			elsif action == "login_reset_password"
				return_title = "Manage Password | AT&T"	
			elsif action == "reset_password_confirmation"
				return_title = "Manage Password | AT&T"	
			elsif action == "reset_password_error"
				return_title = "Set New Password | AT&T"
			elsif action == "login_create"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "routing"
				return_title = "URL not found"
			elsif action == "on_net_consent"
				 return_title = "Consent Request"
			end
		elsif controller == "manage_consent"
			if action == "manage_consent_home"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "applications"
				return_title = "Consent Detail | AT&T"
			elsif action == "consent_application"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "off_net_mc_verify_pin"
				return_title = "Message Sent | AT&T"
			elsif action == "manage_consent"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "mc_off_net_validate_pin"
				return_title = "Message Sent | AT&T"
			elsif action == "on_network"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "mc_verify_onpin"
				return_title = "Message Sent | AT&T"
			elsif action == "on_net_manage_consent"
				return_title = "Message Sent | AT&T"
			elsif action == "mc_resend_pin"
				return_title = "Message Sent | AT&T"
			end
		elsif controller == "consent"
			if action == "consent_app"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "consent_confirmation"
				return_title = "Confirm Page | AT&amp;T"
			elsif action == "login_manage"
				return title = "Signin to AT&T"
			elsif action == "payments"
				return_title = "Consent Request"
			elsif action == "off_net_aoc_consent" || action == "on_net_aoc_consent"
				return_title = "Consent Request"
			elsif action == "aoc_verify_pin"
				return_title = "Message Sent| AT&T"
			elsif action == "aoc_thank_you"
				return_title = "Thank You | AT&T"
			end			
		elsif controller == "on_off_network"
			if action == "off_net_consent"
				 return_title = "Consent Request"
			elsif action == "verify_pin"
				return_title = "Message Sent| AT&T"
			elsif action == "thank_you"
				return_title = "Thank You | AT&T"
			end
		end
		return return_title
	end

	# Method for displaying the logo tiltle.
	def logo_title
		controller=controller_name
		action=action_name
		if controller == "manage_profiles"
			if action == "login_manage" && params[:login] && params[:login] == "mc"
				return_title = "Manage Consent"
			elsif action == "login_manage"
				return_title = "Consent Request"
			elsif action == "login_retry"
				return_title = "Login to AT&T"
			elsif action == "registration" || action == "off_network_registration"
				return_title = "Sign up for AT&T"
			elsif action == "signup_retry"
				return_title = "Sign up for AT&T"
			elsif action == "activation"
				return_title = "Sign up for AT&T"
			elsif action == "resend_mobile_pin"
				return_title = "Sign up for AT&T"
			elsif action == "resend_email_pin"
				return_title = "Sign up for AT&T"
			elsif action == "validate_pin"
				return_title = "Sign up for AT&T"
			elsif action == "signup_create"
				return_title = "Sign up for AT&T"
			elsif action == "signup_confirmation"
				return_title = "Registration"
			elsif action == "reset_password"
				return_title = "Manage Password"
			elsif action == "reset_password_confirmation"
				return_title = "Manage Password"
			elsif action == "reset_password_error"
				return_title = "Set New Password"
			elsif action == "login_create"
				return_title = "Basic Consent Ask | AT&T"
			elsif action == "login_reset_password"
				return_title = "Manage Password"	
			elsif action == "routing"
				return_title = "URL not found"
			elsif action == "on_net_consent"
				 return_title = "Consent Request"
			end
		elsif controller == "manage_consent"
			if action == "manage_consent_home"
				return_title = "Manage Consent"
			elsif action == "applications"
				return_title = "Applications"
			elsif action == "consent_application"
				return_title = "Consent Request"
			elsif action == "off_net_mc_verify_pin"
				return_title = "Verifying"
			elsif action == "manage_consent"
				return_title = "Manage Consent"
			elsif action == "mc_off_net_validate_pin"
				return_title = "Verifying"
			elsif action == "on_network"
				return_title = "Manage Consent"
			elsif action == "mc_verify_onpin"
				return_title = "Verifying"
			elsif action == "on_net_manage_consent"
				return_title = "Verifying"
			elsif action == "mc_resend_pin"
				return_title = "Verifying"
			end
		elsif controller == "consent"
			if action == "consent_app"
				return_title = "Consent by Application"
			elsif action == "consent_confirmation"
				return_title = "Manage Consent"
			elsif action == "login_manage"
				return title = "SignIn | SignUp"
			elsif action == "payments"
				return_title = "Consent Request"
			elsif action == "off_net_aoc_consent"  || action == "on_net_aoc_consent"
				return_title = "Consent Request"
			elsif action == "aoc_verify_pin"
				return_title = "Verifying"
			elsif action == "aoc_thank_you"
				return_title = "Thank You"
			end
		elsif controller == "on_off_network"
			if action == "off_net_consent"
				return_title = "Consent Request"
			elsif action == "verify_pin"
				return_title = "Verifying"
			elsif action == "thank_you"
				return_title = "Thank You"
			end
		end
		return return_title
	end
	def days_in_month(month,year)
	common_year_days_in_month = [nil, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
		 return 29 if month == 2 && Date.gregorian_leap?(year)
		 common_year_days_in_month[month]
	 end
	def months_list
		return ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
	end
	def display_scope_name(scope)
		if scope == "WAP"
			return "WAP Push"
		elsif scope == "DC"
			return "Device Capabilities"
		elsif scope == "TL"
			return "Location"
		elsif scope == "SMS"
			return "SMS messaging"
		elsif scope == "MOBO"
			return "Messaging"
		elsif scope == "MIM"
			return "Message Management"
		else
			return scope
		end
	end
	def display_scope_description(scope)
		if scope == "DC"
			return "may collect and use your device make and model information."
		elsif scope == "TL"
			return "may collect and use your real time AT&T location information."	
		elsif scope == "MOBO"
			return "may send messages from your number. Standard messaging rates apply."
		elsif scope == "MIM"
			return "may retrieve, store & manage messages sent to your number."
		else
			return ""
		end
	end
end
